### ISSUE TITLE
Google/Accounts/Register-App: Follow Googles workflow update

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-admin-documentation#144]
Google has updated the workflow on how to register a OAuth-app. For example, they are asking now for links to legal documents of the host app.

So the process should be re-evaluated to see, what may need to be updated in the shown workflow.

T#10102904
```[tasklist]
### Tasks
- [x] Test connection Zammad-Google
- [x] Restructure Basic Setup section
- [x] Move Content from sub sites to ~"Accounts"~ Basic Setup
- [x] Clean duplicate and stale content
- [x] Rework "Register OAuth App" and "Add Account" sections
- [x] Add screenshots showing the workflow
- [x] Cleanup and rethink/test new structure
```
