### ISSUE TITLE
Update Facebook integration documentation

### ISSUE THREAD

**Issue by thorsteneckel** [zammad/zammad-admin-documentation#2]
Hi @KoJie - could you please update the Zammad Admin documentation on how to integrate Facebook as a channel? We received several questions (https://github.com/zammad/zammad/issues/417 / https://community.zammad.org/t/facebook-app-fehlermeldung/155 ) and should update our documentation accordingly. You can find the new screenshots attached. Feel free to ask any questions.

[Facebook Zammad.zip](https://github.com/zammad/zammad-admin-documentation/files/1599856/Facebook.Zammad.zip)

```[tasklist]
### Tasks
- [x] Setup of new Zammad system
- [x] Check Meta documentation
- [x] Add a new app at Meta's developer page
- [x] Restructure documentation section / add limitations & prerequisites
- [x] Setup facebook channel in Zammad
- [x] Add screenshots
```

**Comment by MrGeneration** [comment]
I am currently moving / organizing a new order within system admin and admin documentation, thus the borders get clearer.

"Parent"-Issue to this is: https://github.com/zammad/zammad-documentation/issues/43
