### ISSUE TITLE
Add custom payload and pre-defined webhook

### ISSUE THREAD

**Issue by dominikklein** [zammad/zammad-admin-documentation#227]
https://github.com/zammad/zammad/issues/4483
- Possibility to add the custom payload to a webhook (with code editor for JSON).

https://github.com/zammad/zammad/issues/4482
- Usage of pre-defined webhooks, which is currently available for:
  - Slack
  - Mattermost
  - RocketChat
(This should also include some hint of removing the article from the notification message)

```[tasklist]
### Tasks
- [x] Document custom payload for webhooks and the associated code editor
- [x] Document distinction of pre-defined webhooks and their fields/payloads
- [x] Add an example for MS Teams (not merged yet)
- [x] Convert Slack integration tutorial into a pre-defined webhook example and include a deprecation warning in the old section
- [x] Review
```
