### ISSUE TITLE
Two-factor authentication (2FA) admin features

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-admin-documentation#242]
```[tasklist]
### Tasks
- [x] Document new settings tab: **Two-factor Authentication**
- [x] Describe **Authenticator App** method in some words
- [x] Explain in more detail **Enforce for roles** setting, re-word the description so it's very clear what it actually does
- [x] Document extension in the user management screen for 2FA methods
- [x] Describe **Security Keys** method in some words
- [x] Describe **Recovery Codes** in some words
- [x] Review
```

**Comment by dvuckovic** [comment]
We will wait with merging this to `pre-release` branch until `latest` is switched to version 6.0.
