### ISSUE TITLE
Add the new VIP attribute to the Organizations section

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-admin-documentation#253]
* Manage > Organizations > VIP
* Check the default WebHook payload for the new VIP attribute under organization hash
* Check the supported variables for the Current User's and Ticket's organization
```[tasklist]
### Tasks
- [x] Manage > Organizations > VIP
- [x] Check the default WebHook payload for the new VIP attribute under organization hash
- [x] Check the supported variables for the Current User's and Ticket's organization
```
