### ISSUE TITLE
Replace screenshots

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-admin-documentation#378]
```[tasklist]
### Tasks
- [x] manage > templates
- [x] manage > trigger > learn by example (2x)
- [x] manage > scheduler
- [x] manage > time-accounting (2x)
- [x] manage > roles (new role)
```
