### ISSUE TITLE
Document the setup of Whatsapp Business Channel

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-admin-documentation#463]
```[tasklist]
### Tasks
- [x] Investigate how other tools document their Whatsapp Integration
- [x] Create a base structure
- [x] Add limitations, prerequisites and a setup guide
- [x] Explain some important restrictions (e.g. 24h window for answers, attachments)
- [x] Document the setup from Meta side, too (at least the basic steps)
```
