### ISSUE TITLE
Explain core workflow conditions

### ISSUE THREAD

**Issue by rolfschmidt** [zammad/zammad-admin-documentation#534]
Maybe we can team up to do a session in the future for some enhancements to explain the core workflow conditions and a couple use cases, since they are very complex.

e.g. confusion:

https://github.com/zammad/zammad/issues/5147

no pressure tho
```[tasklist]
### Tasks
- [x] Add and explain operators
- [x] Check enhancement of core workflows
- [x] Add examples for core workflows
```

**Comment by YetAnotherGerrit** [comment]
Maybe also add a table what condition works with what operator? As in above example the "has changed" is not working with "show", but only "fill in".

**Comment by ralf401** [comment]
**Renaming of:**
- has changed -> just changed
- has changed to -> just changed to

Usage: e.g. prefilling of text. Not usable to show/hide field

**New operators _(only Core Workflow)_:**
- is modified
- is modified to

Usage: e.g. show/hide field. Not usable to prefill text
