### ISSUE TITLE
Rework Channels > Chat section

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-admin-documentation#626]
```[tasklist]
### Tasks
- [x] Remove "anecdotes" and general things about support via chat
- [x] Create a fitting structure (e.g. Intro / Setup / Usage by Agents...)
- [x] Rework text and don't loose already present information
- [x] Add a new screenshot with preview of chat on website
```
