### ISSUE TITLE
Add detailed description of what "inactive" means for the different objects

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-admin-documentation#704]
We offer on a lot of objects and object types to toggle between "active" and "inactive". It is not always intuitive what the consequences are, if you set something to inactive. We should add that.

- Users: there are some information, but incomplete. e.g. Users are not able to login if inactive.
- Groups: there are some information, but incomplete. e.g. Customers can see tickets in inactive groups.
- Roles: missing
- Organizations: seems fine
- Overviews: missing
- Text modules: missing
- Macros: seems fine
- Templates: missing
- Checklist templates: missing
- Trigger: missing
- Webhook: seems fine
- Scheduler: vague
- Report profiles: missing
- Time accounting activity types: missing, e.g. can it still be selected by agents? what about time that has already been booked? is it visible in reports and the ui?
- Email accounts: review needed. Is there more?
- Email filters: missing
- Signatures: missing, e.g. what happens to groups that have a inactive signature set
- Object attributes: missing
- Core workflows: missing

Either on a central site or on their according documentation sites.

Edit RSC:

Relevant places to add a description:

```[tasklist]
### Tasks
- [x] Users
- [x] Groups
- [x] Roles
- [x] Templates => Skipping because it simply can't be selected/used anymore
- [x] Time accounting activity types
- [x] Signatures => No need for explanation. It simply won't be included in answers. It even appears a warning in group config dialog if group is inactive.
- [x] Check some places from the suggestion again
```

For the other features it should be clear what it means when something is disabled.

**Comment by ralf401** [comment]
Hi @YetAnotherGerrit, thanks for your investigation. For sure, this makes sense for some places (e.g.users, groups), but for others I don't see a benefit for the reader because it should be pretty clear (e.g. trigger). This would just bloat up the documentation.

What do you think about just adding the "unclear" items?

**Comment by YetAnotherGerrit** [comment]
> What do you think about just adding the "unclear" items?

Yeah, that makes sense.
