### ISSUE TITLE
Improve and create new Documentation MS365

### ISSUE THREAD

**Issue by tschaefer** [zammad/zammad-admin-documentation#733]
```[tasklist]
### Tasks
- [x] Request Account in Entra
- [x] Rename current documentation to` Microsoft 365 IMAP Email`
- [x] Create new documentation for `Microsoft 365 Graph Email` (see [here](https://github.com/zammad/coordination-scrum/issues/221#issuecomment-2567649400) for required steps)
- [x] Create a parent page and link to IMAP and Graph configuration
- [x] Check if duplicate content can be moved to the parent page
- [x] Document 2 ways: shared mailbox and user mailbox
- [x] Off topic: rename Google channel according to Zammad UI
- [x] Separate it according to review / talk with DV
- [x] Replace screenshot of M365 Graph index
- [x] Replace screenshot of M365 IMAP index
- [x] Add error messages
- [x] Replace links in the app - DV
```
